### ISSUE TITLE
exception with builds as soon as "set build name" option is enabled

### ISSUE THREAD

**Issue by RemiCardona** [jenkinsci/build-name-setter-plugin#55]
Jenkins ver. 2.212
plugin version: 2.0.3 and 2.0.4

```
Started by user unknown or anonymous
Running as SYSTEM
Building remotely on XXX (default) in workspace /home/jenkins/workspace/jenkins-releaser
[ssh-agent] Looking for ssh-agent implementation...
[ssh-agent]   Exec ssh-agent (binary ssh-agent on a remote machine)
$ ssh-agent
SSH_AUTH_SOCK=/tmp/xxx
SSH_AGENT_PID=xxx
[ssh-agent] Started.
Running ssh-add (command line suppressed)
Identity added: /home/jenkins/workspace/jenkins-releaser@tmp/private_key_xxx.key (rsa w/o comment)
[ssh-agent] Using credentials jenkins (Master key)
FATAL: Error creating extended parser class: Class not found
java.io.IOException: Class not found
	at org.objectweb.asm.ClassReader.a(Unknown Source)
	at org.objectweb.asm.ClassReader.<init>(Unknown Source)
	at org.parboiled.transform.AsmUtils.createClassReader(AsmUtils.java:56)
	at org.parboiled.transform.ClassNodeInitializer.process(ClassNodeInitializer.java:62)
	at org.parboiled.transform.ParserTransformer.extendParserClass(ParserTransformer.java:44)
	at org.parboiled.transform.ParserTransformer.transformParser(ParserTransformer.java:39)
	at org.parboiled.Parboiled.createParser(Parboiled.java:54)
Caused: java.lang.RuntimeException: Error creating extended parser class: Class not found
	at org.parboiled.Parboiled.createParser(Parboiled.java:58)
	at org.jenkinsci.plugins.tokenmacro.Parser.process(Parser.java:80)
	at org.jenkinsci.plugins.tokenmacro.Parser.process(Parser.java:74)
	at org.jenkinsci.plugins.tokenmacro.TokenMacro.expand(TokenMacro.java:199)
	at org.jenkinsci.plugins.tokenmacro.TokenMacro.expandAll(TokenMacro.java:237)
	at org.jenkinsci.plugins.tokenmacro.TokenMacro.expandAll(TokenMacro.java:207)
	at org.jenkinsci.plugins.buildnamesetter.Executor.evaluateMacro(Executor.java:75)
	at org.jenkinsci.plugins.buildnamesetter.Executor.setName(Executor.java:30)
	at org.jenkinsci.plugins.buildnamesetter.BuildNameSetter$2.startBuild(BuildNameSetter.java:109)
	at hudson.matrix.DefaultMatrixExecutionStrategyImpl.notifyStartBuild(DefaultMatrixExecutionStrategyImpl.java:214)
	at hudson.matrix.DefaultMatrixExecutionStrategyImpl.run(DefaultMatrixExecutionStrategyImpl.java:129)
	at hudson.matrix.MatrixBuild$MatrixBuildExecution.doRun(MatrixBuild.java:375)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:504)
	at hudson.model.Run.execute(Run.java:1853)
	at hudson.matrix.MatrixBuild.run(MatrixBuild.java:323)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:428)
[PostBuildScript] - [INFO] Executing post build scripts.
[PostBuildScript] - [INFO] Build does not have any of the results [SUCCESS]. Did not execute build step #0.
FATAL: Error creating extended parser class: Class not found
java.io.IOException: Class not found
	at org.objectweb.asm.ClassReader.a(Unknown Source)
	at org.objectweb.asm.ClassReader.<init>(Unknown Source)
	at org.parboiled.transform.AsmUtils.createClassReader(AsmUtils.java:56)
	at org.parboiled.transform.ClassNodeInitializer.process(ClassNodeInitializer.java:62)
	at org.parboiled.transform.ParserTransformer.extendParserClass(ParserTransformer.java:44)
	at org.parboiled.transform.ParserTransformer.transformParser(ParserTransformer.java:39)
	at org.parboiled.Parboiled.createParser(Parboiled.java:54)
Caused: java.lang.RuntimeException: Error creating extended parser class: Class not found
	at org.parboiled.Parboiled.createParser(Parboiled.java:58)
	at org.jenkinsci.plugins.tokenmacro.Parser.process(Parser.java:80)
	at org.jenkinsci.plugins.tokenmacro.Parser.process(Parser.java:74)
	at org.jenkinsci.plugins.tokenmacro.TokenMacro.expand(TokenMacro.java:199)
	at org.jenkinsci.plugins.tokenmacro.TokenMacro.expandAll(TokenMacro.java:237)
	at org.jenkinsci.plugins.tokenmacro.TokenMacro.expandAll(TokenMacro.java:207)
	at org.jenkinsci.plugins.buildnamesetter.Executor.evaluateMacro(Executor.java:75)
	at org.jenkinsci.plugins.buildnamesetter.Executor.setName(Executor.java:30)
	at org.jenkinsci.plugins.buildnamesetter.BuildNameSetter$2.endBuild(BuildNameSetter.java:117)
	at hudson.matrix.MatrixBuild$MatrixBuildExecution.post2(MatrixBuild.java:433)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:635)
	at hudson.model.Run.execute(Run.java:1878)
	at hudson.matrix.MatrixBuild.run(MatrixBuild.java:323)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:428)
Finished: FAILURE
```

I tried with different values for the build name template, makes no difference whatsoever. Is anything else needed to help figure this out? Thanks

**Comment by damianszczepanik** [comment]
Looks like broken installation or Jenkins dependency (token plugin) so I have no idea how to help with this case. Maybe uninstall both plugins and try to install again?

**Comment by RemiCardona** [comment]
So it was an issue in Jenkins itself, somehow. I'm not a Java person so this isn't really my cup of tea. Anyhow it's fixed. Thanks for your help!

https://jenkins.io/changelog/#v2.213
